import React, { Fragment } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { useFavorites } from "../../src/hooks/useFavorites";
import { FavoritesList } from "../../src/components/FavoritesList";
import { PageContainer } from "../../src/components/common/PageContainer";

const BookmarksPage: NextPage = () => {
  const { arrFavorites, handleRemoveFavorite } = useFavorites();
  return (
    <Fragment>
      <Head>
        <title>Github Bookmarks List</title>
        <meta
          name="description"
          content="Generated by create next app for Ennismore tech test"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageContainer>
        <PageContainer.Title>Bookmarked repositories</PageContainer.Title>
        <FavoritesList
          arrFavorites={arrFavorites || []}
          handleRemoveFavorite={handleRemoveFavorite}
        />
      </PageContainer>
    </Fragment>
  );
};

export default BookmarksPage;
