import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import {
  Container,
  Box,
  Typography,
  FormControl,
  TextField,
  Button,
} from "@mui/material";
import { useDispatch, useSelector } from "react-redux";
import { actionGetUserRepos } from "../src/redux/actions/repos";
import { RootStateType, ReposStateType } from "../src/types";
import useSearchForm from "../src/hooks/useSearchForm";
import RepoItem from "../src/modules/RepoItem";
import NextLink from "../src/modules/NextLink";

const Home: NextPage = () => {
  const dispatch = useDispatch();
  const { arrRepos, bLoading, nStrError } = useSelector<
    RootStateType,
    ReposStateType
  >((state) => state.repos);

  const { strUserName, handleSubmit, handleChange, handleReset } =
    useSearchForm((strSearchTerm: string) =>
      dispatch(actionGetUserRepos(strSearchTerm))
    );

  const renderReposList = () => {
    if (bLoading) return <Typography>Loading repos...</Typography>;
    if (nStrError) return <Typography>Error occured: {nStrError}</Typography>;
    if (arrRepos.length === 0) {
      return (
        <Typography>
          Current user does not have any repository. Enter username to search
          for repos.
        </Typography>
      );
    }
    return arrRepos.map((repo) => (
      <NextLink
        key={repo.id}
        href="/repository/[id]"
        as={`/repository/${repo.id}`}
        passHref
      >
        <RepoItem objRepo={repo} />
      </NextLink>
    ));
  };

  return (
    <Container sx={{ backgroundColor: (theme) => theme.bg.main }}>
      <Head>
        <title>Github Repos List</title>
        <meta
          name="description"
          content="Generated by create next app for Ennismore tech test"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box component="main">
        <Typography
          variant="h1"
          textAlign="center"
          sx={{ color: (theme) => theme.text.main }}
        >
          Github Repositories
        </Typography>
        <Box
          sx={{
            display: "flex",
            flexDirection: "column",
            gap: 2,
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <Box component="form" onSubmit={handleSubmit}>
            <FormControl>
              <TextField
                value={strUserName}
                label="username"
                onChange={handleChange}
              />
            </FormControl>
            <Box
              sx={{
                display: "flex",
                flexWrap: "wrap",
                gap: 1,
                justifyContent: "space-between",
                alignItems: "center",
              }}
            >
              <Button type="submit">Search</Button>
              <Button onClick={handleReset} color="warning">
                Reset
              </Button>
            </Box>
          </Box>
          <Box
            sx={{
              display: "flex",
              flexWrap: "wrap",
              gap: 2,
              justifyContent: "center",
              alignItems: "center",
            }}
          >
            {renderReposList()}
          </Box>
        </Box>
      </Box>

      <Box component="footer"></Box>
    </Container>
  );
};

export default Home;
