import { useEffect } from "react";
import { useRouter } from "next/router";
import type { NextPage } from "next";
import Head from "next/head";
import { useSelector, useDispatch } from "react-redux";
import { Container, Box, Typography, IconButton } from "@mui/material";
import { actionGetRepoDetails } from "../../src/redux/actions/repos";
import { RootStateType, ReposStateType } from "../../src/types";
import { getLicenceData } from "../../src/utils";
import useFavorites from "../../src/hooks/useFavorites";
import FavoriteButton from "../../src/modules/common/FavoriteButton";

const RepositoryPage: NextPage = () => {
  const router = useRouter();
  const { query } = router;
  const dispatch = useDispatch();
  const { nObjSelectedRepo } = useSelector<RootStateType, ReposStateType>(
    (state) => state.repos
  );
  const { handleAddFavorite, isFavorite } = useFavorites();

  useEffect(() => {
    if (!query.fullName) return;
    const strFullName = (query.fullName as string[]).join("/");
    dispatch(actionGetRepoDetails(strFullName));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [query]);

  return (
    <Container sx={{ backgroundColor: (theme) => theme.bg.main }}>
      <Head>
        <title>Github Repo Page</title>
        <meta
          name="description"
          content="Generated by create next app for Ennismore tech test"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box component="main">
        <Typography
          variant="h1"
          textAlign="center"
          sx={{
            color: (theme) => theme.text.main,
            fontSize: "26px",
            my: 2,
            fontWeight: 600,
          }}
        >
          Repository page
        </Typography>

        {nObjSelectedRepo && (
          <Box sx={{ display: "flex", flexDirection: "column", rowGap: 1 }}>
            <Typography
              variant="h2"
              sx={{
                fontSize: "22px",
                textAlign: "center",
                color: (theme) => theme.text.main,
                fontWeight: 600,
              }}
            >
              {nObjSelectedRepo?.name}
              <FavoriteButton
                bIsFavorite={isFavorite(nObjSelectedRepo?.full_name)}
                handleClick={() => handleAddFavorite(nObjSelectedRepo)}
              />
            </Typography>
            <Typography variant="caption" sx={{ textAlign: "center" }}>
              Description: {nObjSelectedRepo?.description || "not mentioned"}
            </Typography>
            <Typography variant="caption" sx={{ textAlign: "center" }}>
              License: {getLicenceData(nObjSelectedRepo?.license)}
            </Typography>
          </Box>
        )}
      </Box>
    </Container>
  );
};

export default RepositoryPage;
